export const ActionTypes = {
    FETCH_BOOKS: "FETCH_BOOKS",
    SET_BOOKS: "SET_BOOKS",
    SELECTED_BOOK: "SELECTED_BOOK",
    REMOVE_SELECTED_BOOK: "REMOVE_SELECTED_BOOK",
    ADD_BOOK_TO_WISHLIST: "ADD_BOOK_TO_WISHLIST",
    REMOVE_BOOK_FROM_WISHLIST: "REMOVE_BOOK_FROM_WISHLIST",
    ADD_BOOK_TO_SHOPPINGCART: "ADD_BOOK_TO_SHOPPINGCART",
    REMOVE_BOOK_FROM_SHOPPINGCART: "REMOVE_BOOK_FROM_SHOPPINGCART",
    INCREMENT_ITEMS_IN_SHOPPINGCART: "INCREMENT_ITEMS_IN_SHOPPINGCART",
    DECREMENT_ITEMS_IN_SHOPPINGCART: "DECREMENT_ITEMS_IN_SHOPPINGCART",
};